### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MGadfly**
can you merge these into homework fork for me?  I'm trying to figure out my bug.

### CODE REVIEW

**Comment by MGadfly** [comment]
Thanks for merging for me.

I hit some errors when trying it again tonight.  I haven’t pushed the files back to you yet, I’ll hang on to them for a bit, but I tracked down a few mistakes I made.  I’ll need to send these back your way at some point.

1. Changed team_player_scraper.py to reflect player.offense_rebounds and player.defense_rebounds
2. Changed player_object.py to rename "effective_fg_percent" to “get_effective_fg_percent” at Line 224
3. Changed team_player_scraper.py to cast as floats (including games, but not the percentages) of attributes that are numbers
4. Changed player_object.py's "offensive_rebounds" to "offense_rebounds" inside the get_oreb_thirty function
5. Changed player_object.py's "defensive_rebounds" to "defense_rebounds" inside the get_dreb_thirty function

This is awesome.

On Aug 25, 2018, at 9:52 PM, Jason Woodard <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #3<https://github.com/jasonwoodard/scrape_the_lane/pull/3> into homework.

**Comment by jasonwoodard** [comment]
The properties on the player object likely got a little janked in the merge.  We should (a) sanity check them and (b) consider a less error prone way of doing them.  Right now it's two arrays one of headings and one of properties which is really tedious to spot when they are out of sync.  Short term we should probably put index numbers on them so you can easily side by side them and sanity check.

Cheers,
JW

**Comment by MGadfly** [comment]
Before I sent the merge request it gave me a conflict error and reported four problems. It seemed like fifty problems, but I went through it and resolved a bunch of issues with having two forks of the homework line at different points being merged. After you merged, I cloned it and ran tests and spotted little issues for a couple hours last night. I don’t know why it all of a sudden requires them to be floats, but I’ve fixed the ones that you didn’t on my version and everything is back up and running.
________________________________

**Comment by MGadfly** [comment]
I’ve been looking through the attributes and they look good to me.  The “treb” function is the right one.  It stands for "total rebounds” and we might consider upgrading the “tr” name elsewhere so that it is easier to read both internally and on the export.  There are a couple other attributes that I’d like to change the names to be more in line with standard basketball naming conventions which will shorten them, but I think I shouldn’t worry about that until after the next update to the master branch.

One other thought I had is whether I can mess with the order of the output columns without messing anything up.  I don’t think they have to be output in order anywhere, but I don’t know if there is any function importing them or calling them based on their list position (I didn’t see any).  If so, it might be nice to start with Name, School, HT, Pos, PPG, … and then tuck in some of the needed, but less interesting attributes for an end user at the end of the output.  And I’m also thinking I should take out the self.fg, self.three_point, and self.free_throw from the output.  It was nice for me to have them in there to compare to your split columns to check for bugs, but now they are redundant clutter from the end-user’s perspective.

Was there anything else you wanted me to be looking for as I reviewed them?

On Aug 26, 2018, at 7:24 AM, Jason Woodard <notifications@github.com<mailto:notifications@github.com>> wrote:


If you can take a look at the properties and we can get them aligned I'd like to merge into master. My thought is we should keep master always working,

**Comment by jasonwoodard** [comment]
I was seeing a couple things:

The number of columns in the header was different than the number of
columns in the output that means we're at least short a couple if not slid
against one another one or two places.

we should get very consistent about how we refer to the property names
throughout the code and headers. I don't know what all the abbreviations
mean so I can't tell that FG necessarily equals field goals.

we can also look at chunking up the outputs simply by making multiple
arrays that are smaller composed each logical section. Such as as basic
Player information, derived stats, Etc. we can then concatenate the arrays
as we need them together but individually if they're only ~ 10 items that
have a paired header array of the same number of items that makes it really
simple to spot problems. this also allows us to emit different row flavors
at some Future Point not that we need that now. Does that make sense?

Further question... As we get closer to having scraping solved. Is out
putting csv the ultimate goal?

**Comment by MGadfly** [comment]
I just copied and pasted the header list and emit list next to each other in a spreadsheet and they matchup perfectly in the current homework version.
So whatever the issue was seems to have been fixed with one of the merges.

I think we should get consistent as well, but since I’ve spent twenty years reading basketball stats as the end user, I’m thinking we should try to use the standard conventions wherever we can (first exception being “min” since that’s a built in function on Python and could get confusing).

To me, the csv file is all I need.  It might be cool to try an html output so that it acts like a web page in someone’s browser if they want to view the data but not mess with it in spreadsheet format.  But I’m not sure if it’s worth it.  If we did code in all the advanced stats stuff and exported it to html we could ask Kevin (the guy who programs the game) if he wants to incorporate it into the website.

I might also take a shot at adding the conference number.  It’d require me to jump into the actual parsing section of the code and learn some more stuff, but that might be a good entry to figuring out what you are doing there.



On Aug 26, 2018, at 8:57 AM, Jason Woodard <notifications@github.com<mailto:notifications@github.com>> wrote:

I was seeing a couple things:

The number of columns in the header was different than the number of
columns in the output that means we're at least short a couple if not slid
against one another one or two places.

we should get very consistent about how we refer to the property names
throughout the code and headers. I don't know what all the abbreviations
mean so I can't tell that FG necessarily equals field goals.

we can also look at chunking up the outputs simply by making multiple
arrays that are smaller composed each logical section. Such as as basic
Player information, derived stats, Etc. we can then concatenate the arrays
as we need them together but individually if they're only ~ 10 items that
have a paired header array of the same number of items that makes it really
simple to spot problems. this also allows us to emit different row flavors
at some Future Point not that we need that now. Does that make sense?

Further question... As we get closer to having scraping solved. Is out
putting csv the ultimate goal?

**Comment by MGadfly** [comment]
Do you think it will be too confusing for you if the attribute names were the regular abbreviations for the stat?  I see PPG and read points per game without thinking about it.  For me, it will make it easier to read to convert everything to the regular abbreviations, but I totally understand how someone who doesn’t spend the first part of every day reading through the day’s statistics wouldn’t know the difference from an ORTG a PPG, or STL.

On Aug 26, 2018, at 9:08 AM, Aaron Streepy <aaronstreepy@hotmail.com<mailto:aaronstreepy@hotmail.com>> wrote:

I just copied and pasted the header list and emit list next to each other in a spreadsheet and they matchup perfectly in the current homework version.
So whatever the issue was seems to have been fixed with one of the merges.

I think we should get consistent as well, but since I’ve spent twenty years reading basketball stats as the end user, I’m thinking we should try to use the standard conventions wherever we can (first exception being “min” since that’s a built in function on Python and could get confusing).

To me, the csv file is all I need.  It might be cool to try an html output so that it acts like a web page in someone’s browser if they want to view the data but not mess with it in spreadsheet format.  But I’m not sure if it’s worth it.  If we did code in all the advanced stats stuff and exported it to html we could ask Kevin (the guy who programs the game) if he wants to incorporate it into the website.

I might also take a shot at adding the conference number.  It’d require me to jump into the actual parsing section of the code and learn some more stuff, but that might be a good entry to figuring out what you are doing there.



On Aug 26, 2018, at 8:57 AM, Jason Woodard <notifications@github.com<mailto:notifications@github.com>> wrote:

I was seeing a couple things:

The number of columns in the header was different than the number of
columns in the output that means we're at least short a couple if not slid
against one another one or two places.

we should get very consistent about how we refer to the property names
throughout the code and headers. I don't know what all the abbreviations
mean so I can't tell that FG necessarily equals field goals.

we can also look at chunking up the outputs simply by making multiple
arrays that are smaller composed each logical section. Such as as basic
Player information, derived stats, Etc. we can then concatenate the arrays
as we need them together but individually if they're only ~ 10 items that
have a paired header array of the same number of items that makes it really
simple to spot problems. this also allows us to emit different row flavors
at some Future Point not that we need that now. Does that make sense?

Further question... As we get closer to having scraping solved. Is out
putting csv the ultimate goal?

**Comment by jasonwoodard** [comment]
Awesome. It was late last night when I was looking at it.

The parsing stuff isn't that bad.

**Comment by jasonwoodard** [comment]
It's not about the meaning as much. Although that does help understand what
data type should be in there. it's really about consistent application
points per game should be PPG everywhere.

I think perhaps the next project is to go in and put some documentation on
the functions and property names so that we both can read what they are and
what not it should be a one-time through thing but it'll make a lot of
clarity.

**Comment by MGadfly** [comment]
What do I search for on google hangouts to add you?

On Aug 26, 2018, at 9:36 AM, Jason Woodard <notifications@github.com<mailto:notifications@github.com>> wrote:

It's not about the meaning as much. Although that does help understand what
data type should be in there. it's really about consistent application
points per game should be PPG everywhere.

I think perhaps the next project is to go in and put some documentation on
the functions and property names so that we both can read what they are and
what not it should be a one-time through thing but it'll make a lot of
clarity.

**Pull request merged**
